import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { generateApiKey } from "../services/api";
import { useAuth } from "../context/AuthContext";
import "./DashboardPage.css";

export default function DashboardPage() {
  const { auth, logout, updateApiKey } = useAuth();
  const navigate = useNavigate();
  const [copied, setCopied] = useState(false);
  const [regenerating, setRegenerating] = useState(false);
  const [confirmRegen, setConfirmRegen] = useState(false);
  const [error, setError] = useState("");

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(auth.apiKey);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      setError("Unable to copy to clipboard.");
    }
  };

  const handleRegenerateConfirm = () => {
    setConfirmRegen(true);
    setError("");
  };

  const handleRegenerateCancel = () => {
    setConfirmRegen(false);
  };

  const handleRegenerateExecute = async () => {
    setRegenerating(true);
    setError("");

    try {
      const data = await generateApiKey(auth.token);
      updateApiKey(data.apiKey);
      setConfirmRegen(false);
    } catch (err) {
      if (err.message.includes("401") || err.message.toLowerCase().includes("unauthorized")) {
        logout();
        navigate("/login", { replace: true });
        return;
      }
      setError(err.message || "Failed to regenerate key.");
    } finally {
      setRegenerating(false);
    }
  };

  const handleLogout = () => {
    logout();
    navigate("/", { replace: true });
  };

  const formattedDate = auth?.createdAt
    ? new Date(auth.createdAt).toLocaleDateString(undefined, {
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    : "—";

  /* GENERATED BY AI */
  return (
    <div className="dashboard-page">
      <header className="dashboard-header">
        <div className="dashboard-brand">
          <span>⚾</span>
          <span className="brand-name">DraftKit API</span>
          <span className="brand-sep">/</span>
          <span className="brand-section">Dashboard</span>
        </div>
        <div className="dashboard-user">
          <span className="username-badge">{auth?.username}</span>
          <button className="btn ghost sm" onClick={handleLogout}>
            Logout
          </button>
        </div>
      </header>

      <main className="dashboard-main">
        <section className="dash-card account-card">
          <h2>Account</h2>
          <div className="info-row">
            <span className="info-label">Username</span>
            <span className="info-value">{auth?.username}</span>
          </div>
          <div className="info-row">
            <span className="info-label">Member since</span>
            <span className="info-value">{formattedDate}</span>
          </div>
        </section>

        <section className="dash-card key-card">
          <div className="key-card-header">
            <h2>API Key</h2>
            <span className="key-hint">Use this as your Bearer token on all API requests.</span>
          </div>

          {error && <div className="dash-error">{error}</div>}

          <div className="key-box-wrapper">
            <code className="key-box">{auth?.apiKey}</code>
            <button className="btn ghost sm copy-btn" onClick={handleCopy}>
              {copied ? "Copied!" : "Copy"}
            </button>
          </div>

          <div className="key-usage">
            <pre className="code-block">{`Authorization: Bearer ${auth?.apiKey ?? "<your-api-key>"}`}</pre>
          </div>

          {!confirmRegen ? (
            <button
              className="btn danger sm regen-btn"
              onClick={handleRegenerateConfirm}
              disabled={regenerating}
            >
              Regenerate Key
            </button>
          ) : (
            <div className="regen-confirm">
              <p className="regen-warning">
                This will immediately invalidate your current key. Any existing integrations using it will stop working.
              </p>
              <div className="regen-actions">
                <button
                  className="btn danger sm"
                  onClick={handleRegenerateExecute}
                  disabled={regenerating}
                >
                  {regenerating ? "Regenerating…" : "Yes, regenerate"}
                </button>
                <button
                  className="btn ghost sm"
                  onClick={handleRegenerateCancel}
                  disabled={regenerating}
                >
                  Cancel
                </button>
              </div>
            </div>
          )}
        </section>

        <section className="dash-card docs-card">
          <h2>Quick Reference</h2>
          <div className="endpoint-list">
            {[
              { method: "GET", path: "/api/players", desc: "All players. Optional ?league=AL|NL|MLB" },
              { method: "GET", path: "/api/players/:id", desc: "Single player by MLB ID" },
              { method: "POST", path: "/api/players/value", desc: "Valuate a list of players" },
              { method: "POST", path: "/api/players/value/all", desc: "Valuate all available players" },
              { method: "GET", path: "/api/teams", desc: "All MLB teams. Optional ?league=AL|NL" },
              { method: "GET", path: "/api/teams/:id", desc: "Single team by MLB ID" },
            ].map((ep) => (
              <div key={ep.path} className="endpoint-row">
                <span className={`method-badge method-${ep.method.toLowerCase()}`}>{ep.method}</span>
                <code className="endpoint-path">{ep.path}</code>
                <span className="endpoint-desc">{ep.desc}</span>
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
