import { useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { register as registerApi } from "../services/api";
import { useAuth } from "../context/AuthContext";
import "./AuthPage.css";

export default function RegisterPage() {
  const { auth, login } = useAuth();
  const navigate = useNavigate();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  if (auth?.token) return <Navigate to="/dashboard" replace />;

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError("");
    setLoading(true);

    try {
      const data = await registerApi(username, password);
      login(data);
      navigate("/dashboard", { replace: true });
    } catch (err) {
      setError(err.message || "Registration failed.");
    } finally {
      setLoading(false);
    }
  };

  /* GENERATED BY AI */
  return (
    <div className="auth-page">
      <div className="auth-card">
        <div className="auth-brand">⚾ DraftKit API</div>
        <h2>Create Account</h2>
        <p className="auth-subtitle">Get your API key instantly — no credit card required.</p>

        <form onSubmit={handleSubmit} className="auth-form">
          {error && <div className="auth-error">{error}</div>}
          <label>
            Username
            <input
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              placeholder="choose-a-username"
              required
              disabled={loading}
              autoFocus
            />
          </label>
          <label>
            Password
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="••••••••"
              required
              disabled={loading}
            />
          </label>
          <button type="submit" className="btn primary full-width" disabled={loading}>
            {loading ? "Creating account…" : "Create Account"}
          </button>
        </form>

        <p className="auth-footer">
          Already have an account?{" "}
          <button className="link-btn" onClick={() => navigate("/login")}>
            Sign in here
          </button>
        </p>
      </div>
    </div>
  );
}
