/* GENERATED BY AI */

import { Navigate, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import "./WelcomePage.css";

export default function WelcomePage() {
  const { auth } = useAuth();
  const navigate = useNavigate();

  if (auth?.token) return <Navigate to="/dashboard" replace />;

  return (
    <div className="welcome-page">
      <header className="welcome-header">
        <div className="welcome-brand">
          <span className="brand-icon">⚾</span>
          <div>
            <div className="brand-name">DraftKit API</div>
            <div className="brand-sub">Developer Portal</div>
          </div>
        </div>
      </header>

      <main className="welcome-main">
        <section className="hero">
          <h1>Fantasy Baseball Data API</h1>
          <p>
            Access real-time player stats, team rosters, and auction valuations.
            Sign up to get your API key and start building.
          </p>
          <div className="hero-actions">
            <button className="btn primary" onClick={() => navigate("/register")}>
              Create Free Account
            </button>
            <button className="btn ghost" onClick={() => navigate("/login")}>
              Sign In
            </button>
          </div>
        </section>

        <section className="feature-grid">
          <div className="feature-card">
            <h3>Player Database</h3>
            <p>Query all MLB players by league, position, and stats. Filter by AL, NL, or the full league.</p>
          </div>
          <div className="feature-card">
            <h3>Auction Valuations</h3>
            <p>Get real-time z-score based auction values for any player given your league settings and draft state.</p>
          </div>
          <div className="feature-card">
            <h3>Team Rosters</h3>
            <p>Access current MLB team rosters, depth charts, and metadata for all 30 franchises.</p>
          </div>
        </section>

        <section className="api-example-card">
          <h2>Simple REST API</h2>
          <p>All endpoints return JSON and are secured with Bearer token auth.</p>
          <pre className="code-block">
            <code>{`GET /api/players?league=AL
Authorization: Bearer <your-api-key>`}</code>
          </pre>
        </section>
      </main>
    </div>
  );
}
